services:
    ###> doctrine/doctrine-bundle ###
    database:
        profiles:
            - 'jja_dev'
        ports:
            - '5432'
    ###< doctrine/doctrine-bundle ###

    ###> symfony/mailer ###
    mailer:
        profiles:
            - 'jja_dev'
        image: schickling/mailcatcher
        ports: ['1025', '1080']
    ###< symfony/mailer ###
