name: Symfony
on:
    push:
        branches: [master]
    workflow_run:
        workflows: ["Webpack-build"]
        types:
            - completed
jobs:
    symfony-ovh-deploy:
        runs-on: ubuntu-latest
        steps:
            #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
            # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
            - uses: shivammathur/setup-php@2.30.0
              with:
                  php-version: "8.2"
            - uses: actions/checkout@v4

            - name: OVH
              run: |
                  chmod +x "${GITHUB_WORKSPACE}/.github/scripts/ovh.sh"
                  ${GITHUB_WORKSPACE}/.github/scripts/ovh.sh
              shell: bash
              env:
                  OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER_JJA }}
                  OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD_JJA }}
                  OVH_HOSTING_DOMAIN: ssh.cluster031.hosting.ovh.net
                  REPOSITORY_NAME: JJA_DEV
                  REPOSITORY_URL: https://github.com/JJA-DEV-FR/JJA_DEV.git
